---
title: "Attendee Essentials"
editor: 
  markdown: 
    wrap: 72
---

To ensure a smooth and enjoyable experience at the conference, please take note of the following: 


 
## Badge = Access

* **Please always wear your badge visibly**, as it serves as your identification card throughout the conference. Additionally, **remember to bring your badge to all registered activities to ensure access to the venues**.  
* **No badge = no entry** to sessions, social events, or catering areas.

* Check your badge for abbreviations to see which events you have signed up for, see [List of Badge Abbreviations](badge-abbreviations.qmd). 


## Stay Informed via the App and Online Platform for virtual attendance

* **Access details** (incl. usernames and passwords) will be communicated a few days before the conference. 

* Important updates and reminders will be sent via push notifications through the **official conference App**. 

* We strongly **recommend enabling notifications** and checking the app regularly during the conference days. 


## Info Desk and Registration Desks

* These are located at the Biozentrum and will be open daily from Sunday 24th, August to Thursday 28th, August to assist with inquiries, lost & found, and general guidance.    



## Venue Navigation

* The conference spans two venues: **Biozentrum (University of Basel)** and **BSS Building (ETH Zürich)**, which are conveniently located within close walking distance of each other. 

* Clear signage and staffed info desk (Biozentrum) will help guide you. Please follow directional signs and ask for help if needed. 



## [Support Sustainability](sustainability.qmd) 

* Every onsite attendee will receive **[one reusable bottle](https://www.bwt-shop.ch/de/climatebottle.html) sponsored by our sustainability partner [BWT](https://www.bwt.com/en/)** (Best Water Technology) as part of our shared commitment to reducing single-use plastics. 

* **Bring your reusable water bottle daily**. Water refill stations will be available, but **no bottle = no refill**. We need everyone to take responsibility and be accountable for supporting this sustainable practice. 

* **Paper coffee cups will be collected in dedicated bins** across the venue, as our catering partner will recycle them. *Please support this initiative by disposing of your used cups in the marked bins*. 

* Conference bags are distributed once - please reuse them throughout the week.

* **Your active participation** helps us reduce waste and make ISCB 2025 a greener event. *Every small action counts!* 


## Be Punctual and Prepared

* **Arrive on time** at the designated meeting point for sessions, workshops, and social activities. 

* **Standing at the back of lecture halls is prohibited** due to fire safety regulations. 


## Keynote Sessions – Broadcast Across Venues

* To ensure everyone can enjoy the keynote sessions comfortably and safely, all keynotes will be **broadcast live to all rooms** in both the **Biozentrum** and **ETH** venues. 

* We kindly ask all attendees to **distribute themselves across the available rooms**, as **standing is not permitted** due to safety regulations. Your cooperation helps us maintain a smooth and secure experience for everyone. 



## Welcome Reception

Attendance for the Welcome Reception (Monday evening, 24 August) was limited to 250 participants based on a first-come, first-served basis during registration. If you successfully registered for the reception, your badge will indicate your access (see [List of Badge Abbreviations](badge-abbreviations.qmd)). For those not registered, we encourage you to explore other options in Basel (see e.g. [Restaurants](restaurants.qmd)).

## Social Activities

The various social activities (SA) scheduled for Tuesday afternoon, 25 August, each have individual meeting points and durations. Please refer to the conference booklet or conference app for details about the social activity you have registered for (see [List of Badge Abbreviations](badge-abbreviations.qmd))  


## Certificate of attendance

By default, no certificate of attendance will be provided. If you need one please refer to the information desk. You can leave your name and email there and will get a certificate electronically.

