---
title: "ISCB Conference Awards for Scientists (CASc)"
---

<font color="red">
TODO:

* Update e-mail (scientific@iscb2025.info does not exist yet)
* Add submission form or link to conftool award application track

</font>

The ISCB Conference Awards for Scientists (CASc) are available to biostatisticians 

* from countries that have the National Group of ISCB (Czech Republic, Hungary, Poland, Romania), or 
* from Low, Lower-middle, and Upper-middle income economies, according to the World Bank list for the fiscal year 2025 (https://datahelpdesk.worldbank.org/knowledgebase/articles/906519), 

to provide financial support for their active attendance at the 2025 ISCB Annual Meeting and to present their original, previously unpublished research. Previously awarded applicants by the ISCB or previously awarded research by another scientific institution are therefore not eligible to apply for the 2025 ISCB CASc award. One may, of course, apply for an award in parallel with different scientific bodies, which is not a problem when submitting original research.

Up to three ISCB CASc awards may be granted in 2025. Applications are invited from all areas of biostatistics, including clinical and biomedical research, epidemiology, clinical pharmacology, vaccines research, hospital performance evaluation, survival analysis, causal inference, genomics and system biology, functional analysis, etc. However, applications with purely theoretical content or those involving mere routine data analyses are not encouraged.

The Society has decided to make the CASc competition attractive for eligible applicants. Consequently, for in-person participation in the conference, the 2024 CASc award will include the following:

1. Free registration to the Basel Conference
2. Free accommodation (paid and arranged by the Basel LOC)
3. Free registration to one pre-conference short course of the applicant’s choice
4. Invitation to the Basel Conference Dinner
5. Travel support (economy flights only)

The LOC will organize all of the above benefits other than travel, which must be arranged and paid for by the successful applicant: reimbursement will be made after the conference on production of appropriate receipts.

You can find the guidelines for the application below, and download the application form here. Scientists should carefully follow the application procedure described in the guidelines.

Applicants should submit their abstract (limited to 350 words) using the ISCB45 abstract submission portal. As part of the online abstract submission you are asked to check the box that indicates that you are applying for the Conference Award for Scientists. Once the box is checked, applicants will be asked to upload the documents described in the guidelines.

_Applicants should not register for the conference until they have heard the outcome of their application for the CASc._  Unsuccessful applicants who still wish to attend the conference will remain eligible for the Early Bird rate until three weeks after the outcome of their application is sent to them: see the guidelines for the CASc awards for details.

_The closing date for applications is the same as the general abstract deadline._

## Guidelines for Applicants for the ISCB Conference Awards for Scientists

(a) **ISCB Conference Awards for Scientists** are administered by the National Groups Subcommittee (NG SC) established by the Executive Committee of the ISCB. The aim is to encourage, and support biostatisticians working under financial constraints and enable them to participate in international dialogue.
(b) **Who can apply?** Scientists from countries that have the National Group of ISCB (Czech Republic, Hungary, Poland, Romania) or from Low, Lower-middle, and Upper-middle income economies, according to the World Bank list for the fiscal year 2025 (https://datahelpdesk.worldbank.org/knowledgebase/articles/906519) whose work would benefit from attending the Annual ISCB Meeting. Eligible CASc applicants are the scientists no longer involved in training. Consequently, students are not eligible to apply for the CASc award and they are encouraged to apply for ISCB’s Students Conference Award (StCA). Only original, not previously published or awarded research may be submitted for the award.
(c) **What shall be covered by the award?** The registration fee shall be waived, and inexpensive accommodation will be organised and paid for by the Local Organising Committee (LOC) on behalf of successful applicants. Successful applicants are also eligible to attend one pre-conference course free of charge. The ISCB will invite successful applicants to the Conference Dinner. Finally, inexpensive travel support (economy class) will be provided for all 2025 CASc award recipients. Note that successful applicants will be contacted by email to finalise the free registration to the conference and to the course, and the LOC will be in touch regarding accommodation. Successful applicants will have to arrange and pay for their own travel, with the costs being reimbursed after the conference on production of appropriate receipts. Note that it is obligatory to take an appropriate travel insurance that should cover not being able to travel due to COVID-19 or other illness. In case of travel restrictions imposed by authorities (e.g., a country cancelling all flights) that may not be covered by the insurance, ISCB will reimburse the incurred travel costs. Full travel costs will be reimbursed, provided that these are incurred economically and requested solely for attending the ISCB conference.
(d) **Registration for the Conference.** Applicants for these awards must not register for the conference until they have heard the outcome of their application. It may not be possible to reimburse successful applicants who have already paid their registration. If the awards are announced close to or after the closure of the Early Bird rate, unsuccessful candidates who still wish to attend ISCB45 will remain eligible for the Early Bird rate for three weeks after the NGSC has notified applicants. To take advantage of this please contact the Organisers at scientific@iscb2025.info before attempting to register. Unsuccessful applicants who no longer wish to attend the conference are asked to let the Organisers know by email to scientific@iscb2025.info.
(e) **What are the rules and procedure for making an application?**
    i) Applicants should submit an abstract (limited to 350 words) using the ISCB45 abstract submission portal. As part of the online abstract submission, you are asked to check the box that indicates that you are applying for the 2025 CASc. Once the box is checked applicants will be asked to complete the following steps (ii and iii).
    ii) Applicants need to submit the slides of an intended oral presentation or a complete poster which must concern the application of statistical methodology in clinical or epidemiological research. Applicants who do not have a specialized topic to present are invited to prepare a more general paper with a title such as ‘The need for biostatistical development in my country/region/department’. Applications with purely theoretical content or those representing mere routine analyses of data sets are not encouraged by the ISCB. Only one original submission (i.e. one not previously presented or awarded) per applicant is permissible. Applicants who received the ISCB CASc award in the past are not eligible to apply.
    iii) Applicants should complete the application form available to download here. The presentation/poster and the abstract should be uploaded through this form. The closing date for applications is the same as the general abstract deadline. If the latter is extended the Conference Awards for Scientists deadline is automatically extended to the same date.
(f) **Who will decide about application and how?** The ISCB NG SC will decide the awards promptly, usually within six weeks of the closing date for applications, based on the following criteria: Scientific quality, financial need, value of attendance at the meeting to the region (or to National Groups). Preference will be given to the regions not supported by the ISCB at previous meetings, and those exhibiting a prospect of setting up a new National Group. In selecting the award winners, all members of the NG SC will grade each application independently. In case of ties the Subcommittee will make the final selection through discussion. Chairman of the ISCB NG SC will inform each applicant about the Subcommittee’s decision.