---
title: "ISCB 2025 Student Conference Awards (StCA)"
editor: visual
---

<font color="red">
TODO:

* Add submission form or link to conftool award application track

</font>

The *Student Conference Award (StCA)* is available for *registered postgraduate students in biostatistics* to attend and present a paper at the 46th Annual Conference of the International Society for Clinical Biostatistics, 24th to 28th of August, 2025. Approximately three awards will be granted depending on the number and quality of the applications. Selection will be made on the basis of a summary of a paper to be presented, which should illustrate the application of statistical methodology to clinical or epidemiological research. Results of particular studies are of interest only if the analysis has methodological implications or shows a novel and interesting application of biostatistics.

Applicants should submit their abstract (limited to 350 words) using the ISCB46 abstract submission portal. As part of the online abstract submission you are asked to check the box that indicates that you are applying for the 2025 Student Conference Award. Once the box is checked applicants will be asked to upload the documents described in the guidelines below.

*The closing date for applications is the same as the general abstract deadline. If the latter is extended the Student Conference Award deadline is automatically extended to the same date.*

*Applicants should not register for the conference until they have heard the outcome of their application for the Award. Unsuccessful applicants who still wish to attend the conference will remain eligible for the Early Bird rate until three weeks after the outcome of their application is sent to them: see guidelines for details.*

## Procedures for Selection of Student Conference Award Winners

### Eligibility

(a) Any student registered for a postgraduate degree in biostatistics is eligible to apply for an ISCB Student Conference Award, provided s/he has not been the winner of a previous ISCB Student Conference Award.

(b) The application must relate to original work that has not yet been published and is predominantly the student’s own work. Acceptable topics encompass all areas of biostatistics, both methodological and applied. However, results of particular studies are of interest only if the analysis has methodological implications or shows a novel and interesting application of biostatistics to clinical or epidemiological research.

### Awards

(a) The StCA winners will have their papers scheduled in a dedicated session at the conference. Their status as Award Winners will be indicated in the Conference Programme.
(b) The ISCB will waive the registration fee and the fee for the Conference Dinner for the StCA winners, and will pre-pay their hotel accommodation. The ISCB will also pay for a pre-conference course for StCA winners. Excursions are not included in the award. Normally, it is expected that the StCA winners will pay for travel, which expenses will be reimbursed by ISCB, on the basis of appropriate receipts. Note that it is obligatory to take an appropriate travel insurance that should cover not being able to travel due to COVID-19 or other illness. In case of travel restrictions imposed by authorities (e.g., a country cancelling all flights) that may not be covered by the insurance, ISCB will reimburse the incurred travel costs. Full travel costs will be reimbursed, provided that these are incurred economically and requested solely for attending the ISCB conference. Thus, full advantage of Apex fares, student discounts and so on should be taken where possible. A reimbursement form will be distributed shortly before the conference.
(c) On being selected, a student must submit a travel budget to the StCA Subcommittee Chair by email to [stca\@iscb.info](mailto:stca@iscb.info) for approval. If it proves more economical to make a longer visit in order to secure bargain fares, the cost of extra accommodation and meals will be borne by the ISCB. Once a budget is approved, additional travel costs will be reimbursed only if a convincing case is made of their necessity
(d) In the case of hardship, advance payments will be considered. If for good reason a student has to cancel the trip to attend the Conference, then the ISCB will consider the reimbursement of costs incurred.

## Guidelines for Applicants for the ISCB Student Conference Awards

### Submission Procedure

Applications should consist of the following:

a)  A *short abstract* of the paper prepared according to the ISCB standard conference format, uploaded via the ISCB 2024 Abstract Submission portal.

b)  A *summary of the paper* of no more than 3 double-spaced pages of 12-point text with a maximum of three figures or tables on additional pages. The summary must be in blinded format, i.e., any indication of the student or further authors should not be included.

c)  A *letter from the student’s supervisor*, on official letterhead of the student’s institution, confirming that the student is registered for a postgraduate degree, and that the paper to be presented is original, not previously published, and is predominantly the student’s own work. If the manuscript is co-authored, this letter should also include an indication of the level of involvement of the various authors.

Files containing the above should be uploaded via the ISCB 2024 Abstract submission portal.

Any applications submitted after the due date or incomplete or applications not adhering to the procedures above will not be considered.

### Review

(a) Applications will be judged by the StCA Subcommittee, and applicants will be notified of the results as soon as possible, usually within six weeks of the application submission due date. Evaluation of applications will concern the quality of the research described and its relevance to the application of statistics to clinical and epidemiological research. The presentation of the application materials and the interest of the work to the ISCB members will be taken into consideration. The decisions made by the Subcommittee will be final.
(b) In selecting papers for Awards, each member of the StCA Subcommittee will independently grade each paper submitted. In the case of ties in total grades, the Subcommittee will make the final selection through discussion.
(c) Members of the StCA Subcommittee must declare a conflict of interest in submissions from students with whom they have had substantial contact. Such contact certainly includes students supervised by or in the same department as Subcommittee members and may also include professional contact with the project as well as family links. The Subcommittee member with a conflict of interest in the submission will not grade it, other grades being scaled accordingly, and will not participate in discussions of that submission.
(d) Applicants must be able to travel to the meeting and present their work to be selected Student Conference Award winners.
(e) The Society intends to make three awards. However, the StCA Subcommittee reserves the right to make more or fewer awards, or even none at all, subject to the approval of the ISCB President.
(f) Applications not selected for the Student Conference Awards may still be considered for selection for an oral presentation at a Contributed Paper session or a poster presentation by the Program Committee, since the abstract has been also submitted separately via the conference abstract handling system. This holds unless the applicant indicates that they do not wish to have their submission considered further.
