---
title: "ISCB Conference Attendance Support Program (CASP) at ISCB46"
---

The program will be available to fund participation in the conference for up to 17 attendees. The CASP will pay for registration, accommodation, conference course, conference dinner or conference excursion (recipient’s choice), and travel (all expenses will be prepaid except for travel, which will be reimbursed within two months after attending the conference).

To be eligible, the applicant must be either

-   a current postgraduate student (from any country), and/or
-   a scientist working or attending school in a World-Bank-designated Developing Country (Low, Lower-middle, and Upper-middle income economies, according to [the World Bank list for the fiscal year 2025](https://datahelpdesk.worldbank.org/knowledgebase/articles/906519-world-bank-country-and-lending-groups)) or in a country forming a National Group of the ISCB (Czech Republic, Hungary, Poland, Romania, see [National Groups (NatG) – ISCB](https://iscb.international/national-groups/)).

To apply for the support, an applicant has to

1.  submit an abstract (prepared according to the ISCB46 standard conference format) as a presenting author for either an oral or poster presentation using the [ISCB46 abstract submission system](https://www.conftool.org/iscb2025),
2.  indicate the request for the CASP support at the time of abstract submission (by checking the corresponding checkbox),
3.  at the time of abstract submission, provide a PDF of a letter (on the official letterhead of the institution where the applicant is enrolled/employed) confirming the status of a current postgraduate student (for students) and/or an employment at an institution located in a Developing Country or an ISCB National Group country (for scientists) **by applying to the CASP track (in addition to submitting to the Abstract track) in the conference system**.

Awards will be given to those applicants, whose abstract are selected for presentation (oral or poster) by the Scientific Program Committee (SPC). One award per presentation for one author will be given, without transfer to co-authors. A lottery-based selection will be made by a committee established for that purpose.

Please note that the previous recipients of the Conference Fund for Developing Countries grant are not eligible to apply.

Independently of applying for the CASP, students may also apply for the [Student Conference Award (StCA)](awards-student.qmd). In that case, the confirmation letter required for the StCA (see the StCA application guidelines) can be used for the CASP application, too. If a student is awarded the StCA, he/she will not be considered for the CASP.

In case of questions, please, contact the ISCB Office at the following email: [office\@iscb.international](mailto:office@iscb.international).

