---
title: "Conference Bag"
editor: 
  markdown: 
    wrap: 72
---

## Empowering Inclusive Workplaces

We are proud to share that this year’s conference bags were produced in collaboration with a workplace renowned for its unwavering commitment to diversity and inclusion, particularly in supporting individuals with disabilities.

Headquartered in Rheinfelden, [St. Josefshaus](https://www.sankt-josefshaus.de/) is home to a dedicated team of roughly 1,500 employees, who collectively provide support to around 2,400 people with disabilities and elderly individuals. Their wide range of services spans 15 municipalities and cities, demonstrating a profound commitment to inclusive, person-centered care. The organization’s impactful work includes housing, employment, education, communal living, and care giving.

Their workshops offer meaningful and engaging employment opportunities for individuals who, due to the nature and extent of their disabilities, are unable to participate in the general job market. Within this supportive environment, participants are empowered to discover fulfilling and diverse tasks that match their unique talents—opportunities that foster both a sense of pride and lasting personal satisfaction.

By partnering with this organization, we are not only ensuring high-quality conference materials but also contributing to meaningful social inclusion and empowerment.
We believe this initiative reflects the spirit of collaboration and positive impact that this conference aims to inspire.
