---
title: "ISCB Conference Fund for Developing Countries (CFDC)"
---

<font color="red">
TODO:

* Update e-mail (sotirisroussos@yahoo.co.uk)

</font>

Financial support to participate in the 46<sup>th</sup> Annual Conference of the International Society for Clinical Biostatistics is available to scientists and students from Developing Countries (Low, Lower-middle, and Upper-middle income economies, according to the World Bank list for the fiscal year 2025).

In order to qualify for financial support from the Conference Fund for Developing Countries (CFDC), applicants must submit an abstract for either an oral or poster presentation and be selected by the Scientific Program Committee (SPC) for presentation at ISCB46. Only original and unpublished work that has not been presented previously at a conference will be considered. One award per presentation for one author will be given, without transfer to co-authors. The awarded author’s primary place of employment/enrolment must be in a developing country. **Please note that previous recipients are not eligible to apply.**

Applicants should submit their abstract using the ISCB46 abstract submission portal. As part of the online abstract submission applicants should indicate their request for consideration for financial support from the CFDC by checking the appropriate tick-box. At that time, they should also submit a PDF of a letter of application **(on the official letterhead of the institution where the applicant is enrolled/employed)**.

The evaluation and selection for the CFDC award will be based on the SPC’s decision regarding the abstracts for oral/poster presentation. This will be administered by the CFDC Sub-committee comprising Thomas Jaki (ISCB Vice-President) as Chair, Elaine Pascoe (ISCB Secretary), and Sotiris Roussos (ISCB46 Local Organising Committee [LOC] representative). Any enquiry should be submitted to [sotirisroussos@yahoo.co.uk](sotirisroussos@yahoo.co.uk), indicating in the subject line that the enquiry relates to the CFDC.

Successful applicants who register for virtual participation will have the conference registration fee reimbursed. Those who register for on-site participation will be reimbursed for the cost of the conference registration fee, economy class travel, travel insurance, and reasonable costs for accommodation. Note that **travel insurance is obligatory** and should cover not being able to travel due to COVID-19. In case of travel restrictions imposed by authorities (e.g., a country cancelling all flights) that may not be covered by the insurance, ISCB will reimburse the incurred travel costs. Note that all the costs can only be claimed **after** attendance and presentation at ISCB46 and by presenting appropriate receipts. **Further, claims in excess of €1300 will need prior approval from the ISCB treasurer.** If, after receiving the CFDC support, a change from on-site to virtual attendance is made by choice and not necessity, only the cost of the registration fee will be compensated.

The CFDC will be entirely separate from the Conference Award for Scientists (CASc) administered by the National Groups Sub-committee and from the Student Conference Awards (StCA) administered by the Student Conference Awards Sub-committee. Those who apply for CASc or StCA, but are not selected, will automatically be considered for CFDC support if they qualify, and will be informed accordingly.

**The closing date for applications is the same as the general abstract deadline.**