---
title: "Key Dates"
---

```{r, echo=F, results=F, message=F, warning=F}
Sys.setlocale("LC_ALL", "English")
library(tibble)
library(dplyr)
library(tidyr)
library(readxl)
library(knitr)
library(kableExtra)
library(stringr)
library(lubridate)


key_dates <- list(
  "Pre-conference Courses" =
    tribble(
      ~ Item, ~ Date,
      "Call", ymd("2024-10-04"),
      "Deadline", ymd("2025-01-05"),
      "Notifications sent", ymd("2025-02-11")
    ),
  "Abstract Submissions" =
    tribble(
      ~ Item, ~ Date,
      "Call", ymd("2024-11-27"),
      "Submission opens", ymd("2024-12-09"),
      "Deadline", ymd("2025-02-14"),
      "Notifications sent", ymd("2025-03-21")
    ),
  "Award Applications" =
    tribble(
      ~ Item, ~ Date,
      "Deadline", ymd("2025-02-14"),
      "Notifications sent", ymd("2025-04-15")
    ),
  "Registration" =
    tribble(
      ~ Item1, ~ Item2, ~ Date,
      "Early Bird", "Opens", ymd("2025-03-21"),
      "Early Bird", "Closes", ymd("2025-05-21"),
      "Regular", "Opens", ymd("2025-05-22"),
      "Regular", "Closes", ymd("2025-06-30")
    ),
  "Final File Upload" =
    tribble(
      ~ Item1, ~ Date,
      "Deadline", ymd("2025-08-15"),
    )
)
  


tidy_kable <- function(data, type) {
  if (class(data$Date[0]) == "Date") {
    data <- mutate(data, Date = format(Date, "%A, %d %B %Y"))
  }

  tbl <- data |>
    kable(col.names = c("", "Date"), align = "rl") |>
    kable_styling(
      bootstrap_options = c("striped", "hover", "condensed"),
      full_width = F
    ) |> 
    column_spec(column = 1, width = "160px")
    # column_spec(column = 2, width = "70%") 
    
  return(tbl)
}


```

<!-- ## Invited Sessions -->

<!-- ```{r echo=F, message=F, warning=F} -->
<!-- key_dates[["Invited Sessions"]] |>  -->
<!--   tidy_kable() -->
<!-- ``` -->


## Pre-conference Courses

```{r echo=F, message=F, warning=F}
tbl_data <- 
  key_dates[["Pre-conference Courses"]] |> 
  mutate(Date = format(Date, "%A, %d %B %Y"))

tbl_data[3,2] <- paste0(tbl_data[3,2],"*")

tbl_data |> 
  kable(col.names = c("", "Date"), align = "rl") |>
    kable_styling(
      bootstrap_options = c("striped", "hover", "condensed"),
      full_width = F
    ) |> 
    column_spec(column = 1, width = "160px")
```
[\* Original date: Friday, 07 February 2025]{style="font-size:80%"}


## Abstract Submissions

```{r echo=F, message=F, warning=F}
key_dates[["Abstract Submissions"]] |> tidy_kable()
```
[Note that the abstract submission deadline is *final* and will *not* be extended!]{style="color:red"}

## Awards Applications

```{r echo=F, message=F, warning=F}
key_dates[["Award Applications"]] |> tidy_kable()
```
[Original date for notifications: Friday, 11 April 2025]{style="font-size:80%"}

## Registration

```{r, echo=F, message=F, warning=F}
registration_dates <- key_dates[["Registration"]]
registration_dates |> 
  select(Item2, Date) |> 
  tidy_kable() |> 
  pack_rows(index = table(registration_dates$Item1))

```

## Final File Upload
```{r echo=F, message=F, warning=F}
key_dates[["Final File Upload"]] |> tidy_kable()
```