---
title: "Registration Terms and Conditions - Cancellation Policy"
editor: 
  markdown: 
    wrap: 72
---

## Registration

-   All registration fees are quoted in Euro (€) and taxes are included.
-   Payment in any other currency will not be accepted.
-   Invoices with an address in the European Union must be provided with
    a VAT Number. The invoicing address and VAT number can be set up
    during the registration process.
-   Any modification on VAT number, address or financial documentation,
    requested after the issuing of the invoice or receipt, will result
    in an administrative fee up to € 250.
-   Registration fees are based on the applicable- on the date of
    payment- fee. The prices indicated are only applicable if BOTH the
    registration request AND payment are received before midnight,
    Central European Time (GMT +2), of the relevant registration
    deadline; otherwise, the higher registration fee will apply.
-   A confirmation email will be sent to you upon completion of your
    registration. For your registration to be valid and completed, the
    outstanding amount mentioned should be less or equal to zero.

You are advised to have this confirmation, in your easily accessible
records, should there be a need to present it, at the registration desk
at the Congress venue.

## Payment Details

You may pay by debit / credit card (AMEX is not accepted) or bank
transfer\*. For Early bird registrations, payment has to be received by
21st May 2025 at latest. For Regular registrations, payment has to be
received by 30th June 2025 at latest. In specific cases, you may ask for
extension of payment policy. Please contact
[registrations\@iscb2025.info](mailto:registrations@iscb2025.info)

If the payment is not submitted by the deadline for the fee applicable,
the outstanding amount will be changed to the one that corresponds to
the next registration period.

::: callout-note
As all bank charges (yours and the ones of the beneficiary) are the
responsibility of the payer, you must select ‘OUR’ at the charge options
in order to cover them.
:::

**Bank Details:**\
BANKHAUS BAUER\
POSTFACH 100423, 70003 STUTTGART, GERMANY\
ACCOUNT NUMBER (IBAN): DE32600301000030950007\
BIC: BHBADES1XXX\
Payment reference: "ISCB 46" & DELEGATE' S NAME\
Account holder: CONVIN SA\

Bank charges: Responsibility of the payer

## Cancellation & Alteration Policy

For any cancellation or alteration of your registration, the
Professional Congress Organizer (CONVIN S.A) must be notified in writing
by e-mail at
[registrations\@iscb2025.info](mailto:registrations@iscb2025.info).
Registration cancellations or alterations are subject to the following
conditions:

### Registration Cancellation

-   Until May 31, 2025: Full refund will be given, minus €50
    administrative fee
-   From June 1, 2025 till June 15, 2025 onwards: 30% refund will be
    given minus €50 administrative fee
-   From June 30, 2025: No refund granted.

### Alterations / Name changes

-   Until June 30, 2025 : Name changes are permitted upon payment of a
    €50 administrative fee.
-   From July 1, 2025 onwards: No name changes will be accepted.
-   Non-shows at the Conference will be charged the full fee.
-   A fixed price of €50 will be charged for the replacement of lost
    badges during Conference dates.
-   All refunds will be processed two (2) months after the closing of
    the conference; respective bank charges are the responsibility of
    the delegate.

## Social events/tours cancellation policy

-   Until July 15th 2025: any cancellations for social events/tours are
    permitted without incurring an administrative fee.
-   From July 16th 2025 onwards: cancellations for social events/tours
    will not be accepted, as specific arrangements must be finalized to
    ensure a positive experience for all participants.
