---
title: "Registration"
editor: 
  markdown: 
    wrap: 72
---

General registration info.


## Fees

```{r, echo=F, results=F, message=F, warning=F}
library(dplyr)
library(tidyr)
library(kableExtra)

fees_source <- read.csv(file = "registration-fees.csv") |> 
  mutate(Value = paste(Value, "EUR"))

print_fees <- \(fees_source, registration) {
  fees_source |>
  filter(Type == registration) |>
  select(-Type) |> 
  kbl() |>
  kable_styling(full_width = TRUE) |> 
  collapse_rows(columns = 1:2, valign = "top", ) |> 
  pack_rows(registration, 1, nrow(fees_source), indent = FALSE, background = c("#EAEAEA")) |> 
  row_spec(c(2,4,6), extra_css = "border-bottom: 1px solid grey;", align = "left") |> 
  column_spec(1, extra_css = "border-bottom: 1px solid grey;")
}
```


```{r, echo=F}
gsub("<thead>.*</thead>", "", print_fees(fees_source, "Early registration"))
```
<br>
From Thursday, 22<sup>nd</sup> of May 2025, late registration fees apply:
```{r, echo=F}
gsub("<thead>.*</thead>", "", print_fees(fees_source, "Late registration"))
```

