---
title: "Social Program"
editor: 
  markdown: 
    wrap: 72
---

<!-- * https://cen2023.github.io/home/social.html -->

Information on the social program organised for the ISCB 2025 conference is
summarized below.

## Student Gathering (SUN evening, 24 AUG 2025)

The Student Gathering  will take place at Martkhalle.

<!-- Photos: https://altemarkthalle.ch/wp-content/uploads/2020/02/Markthalle-Info.pdf -->

## Welcome Reception (MON evening, 25 AUG 2025)

The Welcome Reception will take place at the city archives behind the parliament building (Rathaus).
The address is Martinsgasse 2. It is approximately a 20-minute walk.

<!-- MAP TO BE ADDED -->


## Social activities (TUE afternoon, 26 AUG 2025)

### Guided Tour: Street Art Guided tour of Basel

The tri-border area around Basel is regarded as an unrivalled street-art Mecca.
Around 100 artists are active in Basel’s public sphere and transform the city
into a giant open-air museum with works on every corner.

On this guided group tour, you can discover colourful, urban Basel and hear the
stories behind the artworks. Your guide will show you the impressive works of
local artists and take you to see outstanding pieces by internationally renowned
names of the street-art scene.

**Duration:** 1.5 hours.

**Price:** 20 EUR per person.

### Guided Tour: Stories of Basel's Old Town

This traditional tour offers visitors and locals alike a close-up view of Basel.
We will guide you through narrow alleyways and secluded squares, past impressive
buildings and lively and vivid cityscapes, experiencing what has shaped the city
and given it its unique character.

**Duration:** 1.5 hours.

**Price:** 20 EUR per person.

### Guided Tour: Novartis Campus Architecture

The Novartis Campus in Basel is the global headquarters of Novartis. On this tour,
you will get to see the outsides of impressive office and research buildings designed
by famous architects (Diener & Diener, Frank O. Gehry and Herzog & de Meuron, to
name some of them). The walk also takes you through grand parks and past impressive
sculptures, and you will discover the architect Vittorio Magnago Lampugnani’s plan
to enable dialogue and collaboration through architecture and spatial design.

**Duration:** 1.5 hours.

**Price:** 20 EUR per person.

### Confiserie Beschle – Chocolate factory visit and create your own chocolate bar

Embark on a journey through the world of chocolate and learn how professionals
sample and craft this most indulgent treat. Discover the process of growing and
processing cocoa beans, and gain insight into how chocolate is made and refined.
Plus, enjoy the opportunity to taste different types of chocolate and, to top it
all off, create your own chocolate bar.

**Duration:** 2 hours.

**Price:** 85 EUR per person.

### Adventure-filled Scavenger Hunt in Basel

Head out to the prettiest places in the city and solve thrilling riddles.
Discover hidden architectural gems and see long-known things with new eyes.
An iPad guides a group of 6 attendees through the adventure, and the riddle bag
holds further utensils. Additionally to difficulty and duration, there are
several further customisation options to create the perfect experience for you.

**Duration:** 2 hours.

**Price:** 39 EUR per person.

### Crossbow event – William Tell, the central figure of the Swiss Confederacy

Have you ever wondered what it feels like to be William Tell? Learn from professionals on how to use a crossbow and rediscover this traditional Swiss sport. Will your arrow find the apple's core?

**Duration:** 2.5 hours.

**Price:** 39 EUR per person.


## Conference Dinner (WED evening, 27 AUG 2025)

Enjoy a diverse selection of food options at our conference dinner, featuring food booths, a relaxed atmosphere, and complimentary drinks (including beer and wine). 

Detailed information about the conference dinner can be found in the conference booklet.

