---
title: "Environmental Considerations and Ecological Sustainability Concept"
editor: 
  markdown: 
    wrap: 72
---

As part of our commitment to ecological sustainability during the 46th
Annual Conference of the International Society for Clinical
Biostatistics, we are taking several initiatives to ensure our event is
as *green* as possible.

We are thrilled to partner with [BWT](https://www.bwt.com/) (Best Water
Technology) - our esteemed sustainability sponsor. BWT is aligned with
our sustainability vision and will generously provide each conference
attendee with a specially designed Climate Bottle:
<https://www.bwt-shop.ch/de/climatebottle.html>. These reusable bottles
will eliminate the need for single-use plastic, contributing
significantly to our plastic waste reduction goals. Attendees will have
access to water dispensers throughout the venue to refill these bottles,
ensuring a constant supply of fresh water while promoting sustainable
practices.

Further, we are introducing a dedicated collection system for used paper coffee cups. Our catering partner has committed to recycling these cups, ensuring they are processed responsibly. We kindly ask all attendees to support this initiative by disposing of their used coffee cups in the clearly marked recycling bins located throughout the venue. 

Moreover, in an effort to reduce emission and carbon footprint, we have
chosen not to organize buses for social activities. Instead, we
encourage all attendees to utilize Basel's excellent public
transportation system. When you stay overnight in Basel, you will
receive the [BaselCard](https://www.basel.com/en/baselcard) and benefit
from free travel on public transport. The booking confirmation of your
hotel or Airbnb in Basel serves as a free ticket for the transfer from
the airport or train station to your hotel.

Lastly, all lunch boxes made available during the conference will be
fully vegetarian, while we ensure to accommodate vegan or other dietary
requirements as needed.

We are dedicated to making ISCB46 an event to be remembered, not just
for its scientific contributions, but for its dedication to ecological
sustainability as well.
